// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNOuUwUB_mU2FfgjyXA0byNQOG4HTidKo',
    appId: '1:682377629243:web:167875a91ac43d3e08161e',
    messagingSenderId: '682377629243',
    projectId: 'pubplus2-2ca9a',
    authDomain: 'pubplus2-2ca9a.firebaseapp.com',
    storageBucket: 'pubplus2-2ca9a.appspot.com',
    measurementId: 'G-808SWEVQ9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq52EoPa6Az5XQqd0A9cFAiJUwfXq3EOM',
    appId: '1:682377629243:android:c290dc34e3767b7f08161e',
    messagingSenderId: '682377629243',
    projectId: 'pubplus2-2ca9a',
    storageBucket: 'pubplus2-2ca9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQYd8mQxsS3x-l0xXvkXLbmgjmct4AFPY',
    appId: '1:682377629243:ios:60d895fe73449c3508161e',
    messagingSenderId: '682377629243',
    projectId: 'pubplus2-2ca9a',
    storageBucket: 'pubplus2-2ca9a.appspot.com',
    iosClientId: '682377629243-seq9g2gdjrpab1pakgjabpiue15fhce9.apps.googleusercontent.com',
    iosBundleId: 'glory.pubplus.pubplus',
  );
}
